"""Collection names are generated by trusted code, never by a model or HTTP input."""
import hashlib
import json


def private_collection(base, tenant_id, user_id=None):
    digest = hashlib.sha256(json.dumps([base, tenant_id, user_id]).encode()).hexdigest()[:24]
    return "research_private_" + digest
